- name: 拉取安卓16 6.12 GKI 官方内核源码
  run: |
    git clone --depth=1 -b android16-6.12 https://android.googlesource.com/kernel/common/ kernel
    cd kernel
    make defconfig ARCH=arm64
    echo 'CONFIG_LOCALVERSION="-android16-5-g844001fb8721-ab14552068-4k"' >> .config
    echo '# CONFIG_LOCALVERSION_AUTO is not set' >> .config
    echo 'CONFIG_MODVERSIONS=y' >> .config
    echo 'CONFIG_MODULE_SRCVERSION_ALL=y' >> .config
    make modules_prepare ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-